"""
Enhanced Query Handler Module - Sequential Post Processing
Processes posts generated by Goal Handler and converts them into next_post_prediction format
with sequential processing and rate limit handling.
"""

import aiohttp
import asyncio
import json
import re
import os
from typing import Dict, List, Any, Optional
from datetime import datetime
import uuid
from utils.r2_client import R2Client
from utils.status_manager import StatusManager
from utils.logging import logger
from utils.test_filter import TestFilter
from config import GEMINI_CONFIG, R2_CONFIG, STRUCTUREDB_R2_CONFIG
import google.generativeai as genai
from tenacity import retry, stop_after_attempt, wait_exponential
import time

# Configure Gemini with enhanced safety settings
genai.configure(api_key=GEMINI_CONFIG["api_key"])

# Enhanced safety settings to minimize content blocking
safety_settings = [
    {
        "category": "HARM_CATEGORY_HARASSMENT",
        "threshold": "BLOCK_NONE"
    },
    {
        "category": "HARM_CATEGORY_HATE_SPEECH", 
        "threshold": "BLOCK_NONE"
    },
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_NONE"
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_NONE"
    }
]

# Use gemini-1.5-flash for better reliability
model_name = GEMINI_CONFIG.get("model", "gemini-1.5-flash")
if "2.5" in model_name:
    model_name = "gemini-1.5-flash"
    logger.info("🔄 Query Handler using gemini-1.5-flash for better reliability")

model = genai.GenerativeModel(
    model_name=model_name,
    generation_config={
        "max_output_tokens": GEMINI_CONFIG["max_tokens"],
        "temperature": GEMINI_CONFIG["temperature"],
        "top_p": GEMINI_CONFIG["top_p"],
        "top_k": GEMINI_CONFIG["top_k"]
    },
    safety_settings=safety_settings
)

class RateLimiter:
    """Rate limiter with exponential backoff"""
    
    def __init__(self, initial_delay: float = 2.0, max_delay: float = 60.0, backoff_factor: float = 2.0):
        self.current_delay = initial_delay
        self.max_delay = max_delay
        self.backoff_factor = backoff_factor
        self.last_request_time = 0
        self.consecutive_failures = 0
    
    async def wait(self):
        """Wait for the appropriate delay between requests"""
        now = time.time()
        time_since_last = now - self.last_request_time
        
        if time_since_last < self.current_delay:
            wait_time = self.current_delay - time_since_last
            logger.info(f"🕒 Rate limiter waiting for {wait_time:.1f}s")
            await asyncio.sleep(wait_time)
        
        self.last_request_time = time.time()
    
    def update_delay(self, success: bool):
        """Update delay based on request success/failure"""
        if success:
            # On success, gradually reduce delay
            self.consecutive_failures = 0
            self.current_delay = max(2.0, self.current_delay / self.backoff_factor)
        else:
            # On failure, increase delay exponentially
            self.consecutive_failures += 1
            self.current_delay = min(
                self.max_delay,
                self.current_delay * self.backoff_factor
            )
            logger.warning(f"⚠️ Rate limit hit, increasing delay to {self.current_delay:.1f}s")

class SequentialQueryHandler:
    """Sequential Query Handler for processing generated_content posts"""
    
    def __init__(self):
        self.r2_client = R2Client(config=R2_CONFIG)  # Tasks bucket
        self.r2_client_structuredb = R2Client(config=STRUCTUREDB_R2_CONFIG)  # Structuredb bucket
        self.platforms = ["instagram", "twitter", "facebook"]  # Support all three platforms
        self.retry_interval = 10  # 10 seconds retry interval
        self.rate_limiter = RateLimiter()  # Initialize rate limiter
        
    async def run_continuous_processing(self):
        """Main processing loop with 10-second retry interval"""
        logger.info("🚀 Starting Sequential Query Handler with 10-second retry loop")
        
        while True:
            try:
                logger.info("🔍 Scanning for pending posts in generated_content...")
                
                # Scan all platforms for pending posts
                processed_any = False
                
                for platform in self.platforms:
                    platform_processed = await self.scan_platform_for_pending_posts(platform)
                    if platform_processed:
                        processed_any = True
                
                if processed_any:
                    logger.info("✅ Processed pending posts, continuing scan...")
                else:
                    logger.info("💤 No pending posts found, waiting 10 seconds...")
                
                # Wait 10 seconds before next scan
                await asyncio.sleep(self.retry_interval)
                
            except Exception as e:
                logger.error(f"🚨 Error in continuous processing loop: {e}")
                await asyncio.sleep(self.retry_interval)
    
    async def scan_platform_for_pending_posts(self, platform: str) -> bool:
        """Scan a specific platform for pending posts and process one at a time"""
        try:
            platform_prefix = f"generated_content/{platform}/"
            objects = await self.r2_client.list_objects(platform_prefix)
            
            # 🧹 COMPREHENSIVE TEST FILTERING - Filter out all test objects
            production_objects = TestFilter.filter_test_objects(objects)
            
            # Log filtering statistics
            if len(objects) != len(production_objects):
                filtered_count = len(objects) - len(production_objects)
                logger.debug(f"🧹 Query Handler filtered out {filtered_count} test files from {platform}")
            
            # Find posts.json files
            posts_files = []
            for obj in production_objects:
                key = obj["Key"]
                if key.endswith("posts.json"):
                    posts_files.append(key)
            
            logger.debug(f"📁 Found {len(posts_files)} production posts.json files for {platform}")
            
            # Process each file to find pending posts
            for posts_file_key in posts_files:
                # Extract username from path: generated_content/platform/username/posts.json
                parts = posts_file_key.split('/')
                if len(parts) >= 4:
                    username = parts[2]
                    
                    # 🚫 PRODUCTION FILTER - Additional username check
                    if TestFilter.should_skip_processing(platform, username, posts_file_key):
                        continue  # Skip test users
                    
                    # 🎯 PRODUCTION USER - Process posts
                    TestFilter.log_production_user(platform, username, "processing posts")
                    
                    # Check if this file has pending posts
                    if await self.process_file_for_pending_posts(posts_file_key, platform, username):
                        return True  # Processed one post, return to allow retry loop
            
            return False
            
        except Exception as e:
            logger.error(f"🚨 Error scanning {platform} for pending posts: {e}")
            return False
    
    async def process_file_for_pending_posts(self, posts_file_key: str, platform: str, username: str) -> bool:
        """Process a specific posts.json file for pending posts with atomic post claiming"""
        try:
            # 🔒 ATOMIC POST CLAIMING: Atomically read-modify-write to claim a pending post
            posts_data = await self.r2_client.read_json(posts_file_key)
            
            if not posts_data:
                logger.debug(f"📄 Empty or invalid posts file: {posts_file_key}")
                return False
            
            # Find the first pending post and atomically claim it
            pending_post_key = None
            pending_post_value = None
            
            for post_key, post_value in posts_data.items():
                if post_key.startswith("Post_") and isinstance(post_value, dict):
                    if post_value.get("status") == "pending":
                        # 🔒 ATOMIC CLAIM: Mark as processing immediately to prevent race conditions
                        posts_data[post_key]["status"] = "processing"
                        posts_data[post_key]["processing_started_at"] = datetime.now().isoformat()
                        posts_data[post_key]["processor_id"] = f"query_handler_{os.getpid()}"
                        
                        # Atomically write the claim back to R2
                        claim_success = await self.r2_client.write_json(posts_file_key, posts_data)
                        
                        if claim_success:
                            pending_post_key = post_key
                            pending_post_value = post_value
                            logger.info(f"🔒 Atomically claimed pending post: {post_key} for {username} on {platform}")
                            break
                        else:
                            logger.warning(f"⚠️ Failed to claim post {post_key}, may have been claimed by another process")
                            # Restore original status if claim failed
                            posts_data[post_key]["status"] = "pending"
                            return False
            
            if not pending_post_key:
                logger.debug(f"✅ No pending posts available to claim in {posts_file_key}")
                return False
            
            # Process the claimed post
            success = await self.process_single_post(
                posts_file_key, 
                pending_post_key, 
                pending_post_value, 
                platform, 
                username,
                posts_data
            )
            
            return success
            
        except Exception as e:
            logger.error(f"🚨 Error processing file {posts_file_key}: {e}")
            return False
    
    async def process_single_post(
        self, 
        posts_file_key: str,
        post_key: str, 
        post_value: Dict, 
        platform: str, 
        username: str,
        full_posts_data: Dict
    ) -> bool:
        """Process a single pending post and transform it to next_post_prediction format"""
        try:
            logger.debug(f"🔄 Processing {post_key} for {username} on {platform}")
            
            # Load profile data for context
            profile_data = await self.load_profile_data(username, platform)
            
            # Transform the post content using AI
            transformed_post = await self.transform_post_content(
                post_value.get("content", ""),
                platform,
                username,
                profile_data
            )
            
            if not transformed_post:
                logger.error(f"❌ Failed to transform {post_key}")
                return False
            
            # Create next_post_prediction format
            next_post_data = {
                "module_type": "next_post_prediction",
                "platform": platform,
                "username": username,
                "post_data": transformed_post,
                "generated_at": datetime.now().isoformat()
            }
            
            # Save to next_posts directory
            output_success = await self.save_next_post(next_post_data, platform, username)
            
            if output_success:
                # Mark original post as processed
                full_posts_data[post_key]["status"] = "processed"
                full_posts_data[post_key]["processed_at"] = datetime.now().isoformat()
                update_success = await self.r2_client.write_json(posts_file_key, full_posts_data)
                
                if update_success:
                    logger.info(f"✅ Successfully processed {post_key} for {username} on {platform}")
                    return True
                else:
                    logger.error(f"❌ Failed to update status for {post_key}")
                    # Restore to pending if we can't mark as processed
                    full_posts_data[post_key]["status"] = "pending"
                    await self.r2_client.write_json(posts_file_key, full_posts_data)
            else:
                logger.error(f"❌ Failed to save transformed post for {post_key}")
                # Mark as failed if save unsuccessful
                full_posts_data[post_key]["status"] = "failed"
                full_posts_data[post_key]["failed_at"] = datetime.now().isoformat()
                full_posts_data[post_key]["failure_reason"] = "Failed to save transformed post"
                await self.r2_client.write_json(posts_file_key, full_posts_data)
            
            return False
            
        except Exception as e:
            logger.error(f"🚨 Error processing single post {post_key}: {e}")
            
            # 🔧 FAILURE RECOVERY: Mark post as failed to prevent infinite retries
            try:
                current_data = await self.r2_client.read_json(posts_file_key)
                if current_data and post_key in current_data:
                    current_data[post_key]["status"] = "failed"
                    current_data[post_key]["failed_at"] = datetime.now().isoformat()
                    current_data[post_key]["failure_reason"] = f"Exception during processing: {str(e)}"
                    await self.r2_client.write_json(posts_file_key, current_data)
                    logger.info(f"🔧 Marked {post_key} as failed to prevent retries")
            except Exception as recovery_error:
                logger.error(f"🚨 Failed to mark post as failed during recovery: {recovery_error}")
            
            return False
    
    async def load_profile_data(self, username: str, platform: str) -> Optional[Dict]:
        """Load profile data for context in transformation"""
        try:
            profile_key = f"{platform}/{username}/{username}.json"
            profile_data = await self.r2_client_structuredb.read_json(profile_key)
            
            if isinstance(profile_data, list) and len(profile_data) > 0:
                profile_data = profile_data[0]
            
            return profile_data
            
        except Exception as e:
            logger.debug(f"⚠️ Could not load profile data for {username} on {platform}: {e}")
            return None
    
    async def transform_post_content(
        self, 
        content: str, 
        platform: str, 
        username: str, 
        profile_data: Optional[Dict]
    ) -> Optional[Dict]:
        """Transform 3-sentence content into next_post_prediction format using AI with rate limit handling"""
        
        # Validate model configuration
        if not hasattr(model, 'generate_content_async'):
            logger.error(f"🚨 Gemini model not properly configured - missing generate_content_async method")
            return self.create_fallback_transformation(content, platform, username)
        
        # Validate content
        if not content or not content.strip():
            logger.warning(f"⚠️ Empty or invalid content provided, using fallback")
            return self.create_fallback_transformation(content or "", platform, username)
        
        # Create transformation prompt
        prompt = self.create_transformation_prompt(content, platform, username, profile_data)
        
        # Log prompt details for debugging
        logger.debug(f"🔍 Prompt length: {len(prompt)} characters")
        logger.debug(f"🔍 Content length: {len(content)} characters")
        logger.debug(f"🔍 Platform: {platform}, Username: {username}")
        
        max_retries = 5
        retry_count = 0
        empty_response_count = 0  # Track consecutive empty responses
        
        while retry_count < max_retries:
            try:
                # Wait for rate limiter before making request
                await self.rate_limiter.wait()
                
                # Generate transformation using Gemini
                try:
                    response = await asyncio.wait_for(
                        model.generate_content_async(prompt),
                        timeout=60
                    )
                except asyncio.TimeoutError:
                    logger.error(f"🚨 Gemini API request timed out after 60 seconds")
                    raise ValueError("Gemini API request timed out")
                except Exception as api_error:
                    logger.error(f"🚨 Gemini API error: {api_error}")
                    # Check for specific Gemini errors
                    if "quota" in str(api_error).lower():
                        raise ValueError("Gemini API quota exceeded")
                    elif "rate" in str(api_error).lower():
                        raise ValueError("Gemini API rate limit exceeded")
                    else:
                        raise ValueError(f"Gemini API error: {api_error}")
                
                # Log response metadata for debugging
                logger.debug(f"🔍 Response type: {type(response)}")
                if hasattr(response, 'prompt_feedback'):
                    logger.debug(f"🔍 Prompt feedback: {response.prompt_feedback}")
                if hasattr(response, 'candidates') and response.candidates:
                    first_candidate = response.candidates[0]
                    if hasattr(first_candidate, 'finish_reason'):
                        logger.debug(f"🔍 Finish reason: {first_candidate.finish_reason}")
                    if hasattr(first_candidate, 'finish_message'):
                        logger.debug(f"🔍 Finish message: {first_candidate.finish_message}")
                
                # Update rate limiter on success
                self.rate_limiter.update_delay(success=True)

                # Safely extract text from the Gemini response – guards against empty candidates that
                # previously raised `Invalid operation` when accessing `response.text`.
                response_text = ""
                try:
                    # Log response structure for debugging
                    logger.debug(f"🔍 Gemini response structure: {type(response)}")
                    logger.debug(f"🔍 Response attributes: {dir(response)}")
                    
                    # Preferred quick accessor when it is available and valid
                    if getattr(response, "text", None):
                        response_text = response.text
                        logger.debug(f"✅ Using response.text: {len(response_text)} characters")
                    else:
                        logger.debug(f"⚠️ response.text not available, trying manual extraction")
                        # Fallback: manually join all text parts from the first candidate (if any)
                        if getattr(response, "candidates", None):
                            candidates = response.candidates
                            logger.debug(f"🔍 Found {len(candidates)} candidates")
                            if candidates:
                                first_candidate = candidates[0]
                                logger.debug(f"🔍 First candidate attributes: {dir(first_candidate)}")
                                content = getattr(first_candidate, "content", None)
                                if content is not None:
                                    logger.debug(f"🔍 Content attributes: {dir(content)}")
                                    parts = getattr(content, "parts", None)
                                    if parts is not None:
                                        logger.debug(f"🔍 Found {len(parts)} parts")
                                        response_text = "".join(getattr(part, "text", "") for part in parts)
                                        logger.debug(f"✅ Manual extraction: {len(response_text)} characters")
                                    else:
                                        logger.debug(f"⚠️ No parts found in content")
                                else:
                                    logger.debug(f"⚠️ No content found in first candidate")
                            else:
                                logger.debug(f"⚠️ No candidates found")
                        else:
                            logger.debug(f"⚠️ No candidates attribute found")
                except Exception as extract_err:
                    # Log at debug level; we will handle empty response later
                    logger.debug(f"⚠️ Error extracting response text: {extract_err}")
                    logger.debug(f"🔍 Full response object: {response}")

                if not response_text:
                    empty_response_count += 1
                    logger.warning(f"⚠️ Empty response from AI model (attempt {retry_count + 1}/{max_retries}, empty count: {empty_response_count})")
                    
                    # If we're getting consistent empty responses, use fallback
                    if empty_response_count >= 2:
                        logger.error(f"🚨 Consistent empty responses from AI model - switching to enhanced fallback")
                        # Use enhanced fallback for empty responses
                        return self._create_enhanced_fallback_transformation(content, platform, username, profile_data)
                    
                    # For first empty response, add delay and retry
                    await asyncio.sleep(5)
                    # Treat empty response as a transient failure that should be retried
                    raise ValueError("Empty response text from AI model – no valid Parts returned")

                # Reset empty response counter on success
                empty_response_count = 0
                
                # Parse the response into structured data
                transformed_data = self.parse_transformation_response(response_text)
                
                if transformed_data:
                    return transformed_data
                
            except Exception as e:
                retry_count += 1
                error_str = str(e)
                
                # Check if it's a rate limit error
                if "429" in error_str or "quota" in error_str.lower():
                    # Update rate limiter on failure
                    self.rate_limiter.update_delay(success=False)
                    
                    if retry_count < max_retries:
                        logger.warning(f"⚠️ Rate limit hit, attempt {retry_count}/{max_retries}. Waiting before retry...")
                        continue
                
                # Check if it's an empty response error
                if "Empty response text" in error_str:
                    if retry_count < max_retries:
                        logger.info(f"Retrying empty response... Attempt {retry_count}/{max_retries}")
                        # Add delay before retry for empty responses
                        await asyncio.sleep(2)
                        continue
                else:
                    logger.error(f"🚨 Error in AI transformation: {e}")
                    if retry_count < max_retries:
                        logger.info(f"Retrying... Attempt {retry_count}/{max_retries}")
                        continue
                
                break
        
        # If we've exhausted retries or hit a non-recoverable error, use fallback
        logger.warning(f"⚠️ Failed to transform after {retry_count} attempts, using fallback")
        
        # Try one more time with a simplified prompt if we had empty responses
        if empty_response_count > 0:
            logger.info(f"🔄 Attempting simplified prompt as last resort...")
            try:
                simple_prompt = f"Transform this content into a {platform} post: {content}. Respond with JSON: {{\"caption\": \"text\", \"hashtags\": [\"#tag1\", \"#tag2\"], \"call_to_action\": \"text\", \"image_prompt\": \"text\"}}"
                
                response = await asyncio.wait_for(
                    model.generate_content_async(simple_prompt),
                    timeout=30
                )
                
                if hasattr(response, 'text') and response.text:
                    transformed_data = self.parse_transformation_response(response.text)
                    if transformed_data:
                        logger.info(f"✅ Simplified prompt succeeded!")
                        return transformed_data
                        
            except Exception as e:
                logger.debug(f"⚠️ Simplified prompt also failed: {e}")
        
        return self.create_fallback_transformation(content, platform, username)
    
    def create_transformation_prompt(
        self, 
        content: str, 
        platform: str, 
        username: str, 
        profile_data: Optional[Dict]
    ) -> str:
        """Create detailed prompt for content transformation"""
        
        # Extract profile insights if available
        bio = ""
        follower_info = ""
        if profile_data:
            bio = profile_data.get("biography", "")
            followers = profile_data.get("followersCount", 0)
            follower_info = f"Followers: {followers:,}"
        
        # 🏷️ HASHTAG PRESERVATION: Extract existing hashtags from content
        existing_hashtags = self._extract_hashtags_from_content(content)
        hashtag_instruction = ""
        if existing_hashtags:
            hashtag_instruction = f"\nIMPORTANT: The content already includes optimized hashtags: {' '.join(existing_hashtags)}. Please include these hashtags in your response."
        
        prompt = f"""
        Transform this 3-sentence content into a engaging {platform} post for {username}.
        
        ORIGINAL CONTENT: {content}
        
        ACCOUNT INFO:
        - Platform: {platform}
        - Username: {username}
        - Bio: {bio}
        - {follower_info}
        {hashtag_instruction}
        
        TRANSFORMATION REQUIREMENTS:
        1. Create an engaging caption that matches the platform style
        2. Extract and enhance key hashtags (5-8 hashtags total, including any existing ones)
        3. Create a compelling call-to-action
        4. Generate detailed image prompt from the visual description
        
        For {platform}:
        {"- Use casual, engaging tone with emojis" if platform == "instagram" else "- Use conversational, community-focused tone" if platform == "facebook" else "- Use concise, impactful language"}
        {"- Focus on visual storytelling" if platform == "instagram" else "- Focus on community engagement and conversations" if platform == "facebook" else "- Focus on quick engagement"}
        {"- Include relevant hashtags in caption" if platform == "instagram" else "- Use community-focused hashtags" if platform == "facebook" else "- Keep hashtags minimal"}
        
        RESPOND ONLY with this JSON format:
        {{
            "caption": "Engaging post caption with personality and platform optimization",
            "hashtags": ["#hashtag1", "#hashtag2", "#hashtag3", "#hashtag4", "#hashtag5"],
            "call_to_action": "Compelling call-to-action that encourages engagement",
            "image_prompt": "Detailed description for image generation with visual direction and styling"
        }}
        """
        
        return prompt
    
    def _extract_hashtags_from_content(self, content: str) -> List[str]:
        """🏷️ Extract existing hashtags from enhanced content"""
        if not content:
            return []
        
        # Find all hashtags in the content
        hashtags = re.findall(r'#\w+', content)
        logger.debug(f"🏷️ Extracted {len(hashtags)} existing hashtags from content")
        return hashtags
    
    def parse_transformation_response(self, response_text: str) -> Optional[Dict]:
        """Parse AI response into structured format"""
        try:
            # Extract JSON from response with improved parsing
            json_start = response_text.find("{")
            json_end = response_text.rfind("}") + 1
            
            if json_start >= 0 and json_end > json_start:
                json_str = response_text[json_start:json_end]
                
                # 🔧 JSON CLEANUP: Clean up common JSON formatting issues
                json_str = json_str.strip()
                # Remove any trailing commas that might cause parsing issues
                json_str = re.sub(r',(\s*[}\]])', r'\1', json_str)
                
                try:
                    data = json.loads(json_str)
                except json.JSONDecodeError as json_error:
                    logger.error(f"🚨 JSON parsing failed: {json_error}")
                    logger.debug(f"Problematic JSON: {json_str[:300]}...")
                    
                    # 🔧 JSON RECOVERY: Try alternative parsing approaches
                    return self._attempt_json_recovery(json_str, response_text)
                    
                # Ensure data is a dictionary
                if not isinstance(data, dict):
                    logger.error(f"🚨 AI response is not a dictionary: {type(data)}")
                    return None
                
                # Validate required fields with detailed logging
                required_fields = ["caption", "hashtags", "call_to_action", "image_prompt"]
                missing_fields = [field for field in required_fields if field not in data]
                
                if not missing_fields:
                    logger.debug(f"✅ All required fields present in AI response")
                    return data
                else:
                    logger.error(f"❌ Missing required fields in AI response: {missing_fields}")
                    logger.debug(f"Available fields: {list(data.keys())}")
                    logger.debug(f"Response snippet: {str(data)[:200]}...")
                    
                    # 🔧 FIELD RECOVERY: Try to recover missing fields with reasonable defaults
                    recovered_data = data.copy()
                    
                    if "caption" not in recovered_data:
                        recovered_data["caption"] = "Engaging content coming your way!"
                        logger.info("🔧 Recovered missing 'caption' field")
                        
                    if "hashtags" not in recovered_data:
                        recovered_data["hashtags"] = ["#Content", "#Engagement", "#Quality"]
                        logger.info("🔧 Recovered missing 'hashtags' field")
                        
                    if "call_to_action" not in recovered_data:
                        recovered_data["call_to_action"] = "What do you think? Share your thoughts!"
                        logger.info("🔧 Recovered missing 'call_to_action' field")
                        
                    if "image_prompt" not in recovered_data:
                        recovered_data["image_prompt"] = "High-quality, engaging visual content with professional photography"
                        logger.info("🔧 Recovered missing 'image_prompt' field")
                    
                    logger.info(f"🔧 Successfully recovered {len(missing_fields)} missing fields")
                    return recovered_data
                    
        except Exception as e:
            logger.error(f"🚨 Error parsing AI response: {e}")
            
        return None
    
    def _attempt_json_recovery(self, malformed_json: str, original_response: str) -> Optional[Dict]:
        """Attempt to recover from malformed JSON responses"""
        try:
            logger.info("🔧 Attempting JSON recovery from malformed response")
            
            # Try to extract individual fields using regex patterns
            recovered_data = {}
            
            # Extract caption
            caption_match = re.search(r'"caption"\s*:\s*"([^"]*)"', malformed_json, re.IGNORECASE)
            if caption_match:
                recovered_data["caption"] = caption_match.group(1)
            
            # Extract hashtags
            hashtags_match = re.search(r'"hashtags"\s*:\s*\[([^\]]*)\]', malformed_json, re.IGNORECASE)
            if hashtags_match:
                hashtags_str = hashtags_match.group(1)
                # Parse hashtags array
                hashtags = re.findall(r'"([^"]*)"', hashtags_str)
                recovered_data["hashtags"] = hashtags
            
            # Extract call to action
            cta_match = re.search(r'"call_to_action"\s*:\s*"([^"]*)"', malformed_json, re.IGNORECASE)
            if cta_match:
                recovered_data["call_to_action"] = cta_match.group(1)
            
            # Extract image prompt
            image_match = re.search(r'"image_prompt"\s*:\s*"([^"]*)"', malformed_json, re.IGNORECASE)
            if image_match:
                recovered_data["image_prompt"] = image_match.group(1)
            
            # Check if we recovered enough data
            if len(recovered_data) >= 2:  # At least 2 fields recovered
                logger.info(f"🔧 Successfully recovered {len(recovered_data)} fields from malformed JSON")
                
                # Fill in missing fields with defaults
                if "caption" not in recovered_data:
                    recovered_data["caption"] = "Engaging content coming your way!"
                if "hashtags" not in recovered_data:
                    recovered_data["hashtags"] = ["#Content", "#Engagement"]
                if "call_to_action" not in recovered_data:
                    recovered_data["call_to_action"] = "What do you think?"
                if "image_prompt" not in recovered_data:
                    recovered_data["image_prompt"] = "High-quality engaging visual content"
                
                return recovered_data
            else:
                logger.warning("🚨 JSON recovery failed, insufficient data recovered")
                return None
                
        except Exception as e:
            logger.error(f"🚨 Error during JSON recovery: {e}")
            return None
    
    def _create_enhanced_fallback_transformation(self, content: str, platform: str, username: str, profile_data: Optional[Dict] = None) -> Dict:
        """Create enhanced fallback transformation when AI model fails consistently"""
        
        logger.info(f"🎯 Creating enhanced fallback transformation for {username} on {platform}")
        
        try:
            # Extract content elements
            sentences = content.split('. ')
            base_content = sentences[0] if sentences else content[:50]
            
            # Platform-specific transformations
            if platform.lower() == "instagram":
                caption = f"✨ {base_content}... Ready to make an impact! 🚀"
                hashtags = ["#Instagram", "#Content", "#Engagement"]
                call_to_action = "Double-tap if you agree! 💜"
                image_prompt = f"Vibrant Instagram-style visual featuring {base_content.lower()}, modern aesthetic with bright colors and engaging composition"
                
            elif platform.lower() == "twitter":
                caption = f"🔥 {base_content}... What's your take? 🤔"
                hashtags = ["#Twitter", "#Discussion"]
                call_to_action = "RT and share your thoughts!"
                image_prompt = f"Clean Twitter-optimized graphic with {base_content.lower()}, minimalist design with bold typography"
                
            elif platform.lower() == "facebook":
                caption = f"💭 {base_content}... Let's discuss this together! 🗣️"
                hashtags = ["#Facebook", "#Community"]
                call_to_action = "Share your thoughts in the comments!"
                image_prompt = f"Facebook-friendly visual showcasing {base_content.lower()}, warm and inviting community-focused design"
                
            else:
                caption = f"🎯 {base_content}... Join the conversation!"
                hashtags = ["#SocialMedia", "#Content"]
                call_to_action = "What do you think?"
                image_prompt = f"Professional social media graphic featuring {base_content.lower()}"
            
            # Use profile data if available for personalization
            if profile_data:
                followers = profile_data.get("followersCount", 0)
                if followers > 10000:
                    call_to_action = "Tag a friend who needs to see this! 👇"
                elif followers > 1000:
                    call_to_action = "Save this post for later! 📌"
            
            return {
                "module_type": "next_post_prediction",
                "platform": platform,
                "username": username,
                "post_data": {
                    "caption": caption,
                    "hashtags": hashtags,
                    "call_to_action": call_to_action,
                    "image_prompt": image_prompt
                },
                "generated_at": datetime.now().isoformat(),
                "fallback_used": True,
                "fallback_method": "enhanced_ai_failure_fallback"
            }
            
        except Exception as e:
            logger.error(f"🚨 Error in enhanced fallback transformation: {e}")
            return self.create_fallback_transformation(content, platform, username)

    def create_fallback_transformation(self, content: str, platform: str, username: str) -> Dict:
        """Create fallback transformation when AI fails"""
        
        # Extract sentences
        sentences = content.split('. ') if content else []
        
        # Create basic caption
        if len(sentences) >= 2:
            caption = '. '.join(sentences[:2])
        else:
            caption = content if content else "Exciting content coming your way!"
        
        # Basic hashtags based on platform
        if platform == "instagram":
            hashtags = ["#Instagram", "#Content", "#Engagement", "#Quality", "#Brand"]
        elif platform == "facebook":
            hashtags = ["#Facebook", "#Community", "#SocialConnection", "#Engagement", "#Content"]
        else:  # Twitter
            hashtags = ["#Twitter", "#Update", "#Engagement"]
        
        # Extract image prompt from 3rd sentence or create default
        image_prompt = "High-quality, engaging visual content"
        if len(sentences) >= 3:
            third_sentence = sentences[2]
            if any(word in third_sentence.lower() for word in ["visual", "image", "photo", "look", "show"]):
                image_prompt = third_sentence
        
        return {
            "caption": caption,
            "hashtags": hashtags,
            "call_to_action": "What do you think? Share your thoughts!",
            "image_prompt": image_prompt
        }
    
    async def save_next_post(self, next_post_data: Dict, platform: str, username: str) -> bool:
        """Save transformed post to next_posts directory with a collision-proof naming scheme.

        Uses a persistent counter file to maintain a monotonically increasing sequence number
        and appends a millisecond timestamp to ensure uniqueness even if files are later deleted.
        """
        try:
            # Create output directory path
            output_dir = f"next_posts/{platform}/{username}/"
            counter_key = f"{output_dir}.counter.json"
            
            # Determine the next sequence number using a persistent counter with enhanced error handling
            post_number = 1
            try:
                counter_data = await self.r2_client.read_json(counter_key)
                if isinstance(counter_data, dict) and isinstance(counter_data.get("last_seq"), int):
                    post_number = counter_data["last_seq"] + 1
                    logger.info(f"📊 Read existing counter: post number {post_number} for {username}")
                else:
                    # Fallback: infer max from existing files once
                    objects = await self.r2_client.list_objects(output_dir)
                    max_seq = 0
                    for obj in objects:
                        key = obj.get("Key", "")
                        # match campaign_next_post_<seq>[_...].json
                        m = re.search(r"campaign_next_post_(\d+)", key)
                        if m:
                            try:
                                max_seq = max(max_seq, int(m.group(1)))
                            except Exception:
                                pass
                    post_number = max_seq + 1 if max_seq > 0 else 1
                    logger.info(f"📊 Inferred post number {post_number} from existing files for {username}")
                    
                    # Initialize counter file for future use
                    await self.r2_client.write_json(counter_key, {
                        "last_seq": post_number - 1,  # Current post will be this number
                        "created_at": datetime.now().isoformat(),
                        "updated_at": datetime.now().isoformat()
                    })
                    logger.info(f"🔧 Initialized counter file for {username}")
                    
            except Exception as e:
                # Check if it's a "NoSuchKey" error (missing counter file)
                if "NoSuchKey" in str(e) or "does not exist" in str(e):
                    logger.info(f"📊 Counter file doesn't exist for {username}, creating new one")
                    post_number = 1
                    # Create initial counter file
                    try:
                        await self.r2_client.write_json(counter_key, {
                            "last_seq": 0,  # Will be incremented to 1
                            "created_at": datetime.now().isoformat(),
                            "updated_at": datetime.now().isoformat()
                        })
                        logger.info(f"✅ Created initial counter file for {username}")
                    except Exception as create_error:
                        logger.warning(f"⚠️ Failed to create counter file: {create_error}")
                else:
                    logger.error(f"❌ Error reading counter file: {e}")
                    post_number = 1
                logger.info(f"📊 Starting with campaign post number: {post_number} for {username}")
            
            # Create output filename with sequence and millisecond timestamp to avoid reuse
            millis = int(datetime.now().timestamp() * 1000)
            output_key = f"{output_dir}campaign_next_post_{post_number}_{millis}.json"
            
            # Save the transformed post
            success = await self.r2_client.write_json(output_key, next_post_data)
            
            if success:
                logger.info(f"💾 Saved transformed campaign post to: {output_key}")
                # Persist the updated counter
                await self.r2_client.write_json(counter_key, {"last_seq": post_number, "updated_at": datetime.now().isoformat()})
                return True
            else:
                logger.error(f"❌ Failed to save to: {output_key}")
                return False
                
        except Exception as e:
            logger.error(f"🚨 Error saving campaign next_post: {e}")
            return False

# Main execution
async def main():
    """Main entry point for sequential query handler"""
    handler = SequentialQueryHandler()
    await handler.run_continuous_processing()

if __name__ == "__main__":
    asyncio.run(main())